{"name": "Adıyaman'da Sosyal Yardımlaşma ve Dayanışma Vakfı tarafından dağıtılan yardımlara ilişkin Başbakandan sorusu ve Aile ve Sosyal Politikalar Bakanı Ayşen Gürcan'ın cevabı (7/77)", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d25/c002/tbmm25002001.pdf", "sayfa": ["174:176"]}]}
{"name": "Sosyal Yardımlaşma ve Dayanışma Vakıfları tarafından yapılan yardımlara ilişkin sorusu ve Devlet Bakanı ve Başbakan Yardımcısı Hayati Yazıcı’nın cevabı (7/52)", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d23/c002/tbmm23002001.pdf", "sayfa": ["171:173"]}]}
{"name": "Müsteşar yardımcılarına ilişkin sorusu ve Millî Eğitim Bakanı Hüseyin Çelik’in cevabı (7/14)", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d23/c002/tbmm23002001.pdf", "sayfa": ["142:143"]}]}
{"name": "Makam aracı tahsis edilen daire başkanı ve genel sekreter yardımcılarına ilişkin sorusu ve Türkiye Büyük Millet Meclisi Başkanı Köksal Toptan’ın cevabı (7/79)", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d23/c002/tbmm23002001.pdf", "sayfa": ["192"]}]}
{"name": "AB Komisyonu Başkanlığı Tezkeresi-Komisyonun eşbaşkan ve eşbaşkan yardımcılıkları seçimini yaptığına İlişkin (3/228)", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d21/c002/tbmm21002018.pdf", "sayfa": ["159"]}]}
{"name": "Mahallî İdareler Fonundan 1995 yılı içinde illere yapılan yardımlara ilişkin sorusu ve İçişleri Bakanı Ülkü Güney'in cevabı (7/323)", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d20/c002/tbmm20002031.pdf", "sayfa": ["669:670"]}]}
{"name": "Bayır Bucak bölgesinde birçok köyün Rus birlikleri tarafından işgal edildiğine ve Hükûmetin Türkmenlere gerekli yardımları yapmasını talep ettiğine ilişkin açıklaması", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d26/c019/tbmm26019103.pdf", "sayfa": ["565"]}]}
{"name": "Antalya-Kale İlçesinde yaşanan doğal afetle ilgili yardım yapılıp yapılmayacağına ilişkin sorusu ve Tarım ve Köyişleri Bakanı Sami Güçlü'nün cevabı (7/44)", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d22/c002/tbmm22002017.pdf", "sayfa": ["264:266"]}]}
{"name": "Trakya illerinin kuraklık yardımı kapsamına alınıp alınmayacağına ilişkin sorusu ve Tarım ve Köyişleri Bakanı Mehmet Mehdi Eker’in cevabı (7/48)", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d23/c003/tbmm23003012.pdf", "sayfa": ["293:299"]}]}
{"name": "Gezi olaylarının kitleselleşmesinden telaşlanan zamanın Hükûmetinin birtakım terör örgütlerinden ve PKK'nın İmralı'daki elebaşından yardım istediğine ilişkin açıklaması", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d26/c018/tbmm26018096.pdf", "sayfa": ["305"]}]}
{"name": "Maliye Bakanlığının, şeffaflık ilkesi gereğince belediyelere yaptığı yardımları açıklaması gerektiğine ve Türkiye Cumhuriyeti'nin kuruluş yıllarında da ilkokullarda ders kitaplarının parasız verildiğine ilişkin açıklaması", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d26/c010/tbmm26010053.pdf", "sayfa": ["463"]}]}
{"name": "Mersin Milletvekili Mehmet Şandır’ın, İstanbul Milletvekili Mustafa Sezgin Tanrıkulu’nun ve Kayseri Milletvekili Pelin Gündeş Bakır’ın, 23 Ekim 2011 tarihinde Van ilinin Erciş ilçesi merkez üssü olmak üzere meydana gelen depreme, ilişkin gündem dışı konuşmaları ve Muş Milletvekili Sırrı Sakık’ın, Başbakan ve bir grup bakanın deprem bölgesinde yaptıkları durum değerlendirmesinde belediye başkanı ve yardımcısıyla diyalog kurulmadığına, İstanbul Milletvekili Halide İncekara’nın, deprem nedeniyle yapılan yardım kampanyalarına, Hakkâri Milletvekili Adil Kurt’un, deprem bölgesi imar planının incelemeye alınması gerektiğine, Gaziantep Milletvekili Ali Serindağ’ın, deprem nedeniyle hayatını kaybeden vatandaşlarımıza Allah’tan rahmet, yaralılara acil şifalar dilediğine ve imar planı sorumluları hakkında işlem yapılması gerektiğine, İstanbul Milletvekili Abdullah Levent Tüzel’in, Bursa Milletvekili Sena Kaleli’nin, İstanbul Milletvekili Ferit Mevlüt Aslanoğlu’nun, Tokat Milletvekili Orhan Düzgün’ün ve İstanbul Milletvekili Mehmet Akif Hamzaçebi’nin, Van ilinin Erciş ilçesi merkez üssü olmak üzere meydana gelen deprem nedeniyle hayatını kaybeden vatandaşlarımıza Allah’tan rahmet, yaralılara acil şifalar dilediğine, ilişkin açıklamaları dolayısıyla", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d24/c003/tbmm24003011.pdf", "sayfa": ["43:48"]}]}
{"name": "Şırnak ilinin Uludere ilçesinin sınır kesiminde yapılan hava operasyonunda 35 vatandaşımızın hayatını kaybetmesi ve açılan soruşturma ile bu vatandaşlarımızın geride kalan yakınlarına yapılacak yardımlara ilişkin Hükûmet adına açıklaması ", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d24/c010/tbmm24010046.pdf", "sayfa": ["209:213"]}]}
{"name": "Van ilinde meydana gelen depremlerde, arama ve kurtarma çalışmaları, yardımların ulaştırılması, hasar tespiti ve süreçteki diğer hizmetlerin yerine getirilmesinde etkin koordinasyon sağlayamadığı iddiasıyla Başbakan Yardımcısı Beşir Atalay hakkında gensoru açılmasına ilişkin önergenin (11/6) ön görüşmeleri münasebetiyle", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d24/c005/tbmm24005027.pdf", "sayfa": ["753:758"]}]}
{"name": "Somali’ye yapılan yardımlara ilişkin açıklaması", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d24/c002/tbmm24002003.pdf", "sayfa": ["107"]}]}
{"name": "Dinar depreminden sonra yapılan yardımlara ilişkin sorusu ve Bayındırlık ve İskân Bakanı Mehmet Keçeciler'in cevabı (7/298)", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d20/c003/tbmm20003034.pdf", "sayfa": ["71:73"]}]}
{"name": "Konya'daki belediyelere yapılan yardımlara ilişkin sorusu ve Çevre Bakanı Mustafa R. Taşar'ın cevabı (7/494)", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d20/c003/tbmm20003034.pdf", "sayfa": ["86:87"]}]}
{"name": "Konya'daki belediyelere yapılan yardımlara ilişkin sorusu ve Çevre Bakanı Mustafa R. Taşar'ın cevabı (7/495)", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d20/c003/tbmm20003034.pdf", "sayfa": ["87:88"]}]}
{"name": "Konya'daki belediyelere yapılan yardımlara ilişkin sorusu ve Malîye Bakanı Lutfullah Kayalar'ın cevabı (7/500)", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d20/c003/tbmm20003034.pdf", "sayfa": ["88:89"]}]}
{"name": "Konya'daki belediyelere yapılan yardımlara ilişkin sorusu ve Malîye Bakanı Lutfullah Kayalar'ın cevabı (7/501)", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d20/c003/tbmm20003034.pdf", "sayfa": ["89:90"]}]}
{"name": "Ve 34 milletvekilinin, ders kitaplarındaki ve yardımcı kitaplardaki cinsiyete dayalı ayrımcılık ögelerinin araştırılması amacıyla Meclis araştırması açılmasına ilişkin (10/29)  Okunması", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d23/c003/tbmm23003015.pdf", "sayfa": ["465:467"]}]}
{"name": "Ordu Milletvekili Rıdvan Yalçın’ın fındık üreticilerinin alacaklarının ödenmesine ilişkin Başbakandan (6/168); TMO’nun fındık alımına (6/164); Bilecik Milletvekili Yaşar Tüzün’ün kuraklık kapsamına alınan illere (6/10); Antalya Milletvekili Tayfur Süner’in çiftçilere yapılan “kuraklık yardımı”na (6/19); Ardahan Milletvekili Ensar Öğüt’ün işsiz ziraat mühendislerine (6/147); Edirne Milletvekili Cemaleddin Uslu’nun kuraklıktan etkilenen ayçiçeği üreticilerinin desteklenmesine (6/161); Karaman Milletvekili Hasan Çalış’ın kuraklıktan etkilenen sebze ve meyve yetiştiricilerinin desteklenmesine (6/162); Sulama kooperatiflerinin borçlarına (6/170); Manisa Milletvekili Mustafa Enöz’ün kuraklıktan etkilenen çiftçilerin desteklenmesine (6/167); ilişkin sözlü soru önergeleri münasebetiyle", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d23/c004/tbmm23004019.pdf", "sayfa": ["477:484", "486:488"]}]}
{"name": "Ve 100 milletvekilinin, kamu vakıfları ile kamu bünyesinde kurulu dernek ve yardımlaşma sandıkları konusunun araştırılarak, bu oluşumlardan kaynaklanan sorunların araştırılarak alınması gereken önlemlerin belirlenmesi amacıyla Meclis araştırması açılmasına ilişkin önergesi (10/28)", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d22/c003/tbmm22003027.pdf", "sayfa": ["574:578"]}]}
{"name": "Memurlara yapılan kira yardımının artırılıp artırılmayacağına ilişkin sözlü soru önergesi ve Çevre Bakanı İmdat Sütlüoğlu'nun cevabı (6/60)", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d22/c003/tbmm22003027.pdf", "sayfa": ["593:594"]}]}
{"name": "Konya'daki belediyelere yapılan yardımlara ilişkin sorusu ve Bayındırlık ve İskân Bakanı Mehmet Keçeciler'in cevabı (7/498,499)", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d20/c003/tbmm20003037.pdf", "sayfa": ["419:420"]}]}
{"name": "Çiftçilere yapılan “kuraklık yardımı”na (6/19) ilişkin sözlü soru önergesine Tarım ve Köyişleri Bakanı Mehmet Mehdi Eker’in cevabı münasebetiyle", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d23/c004/tbmm23004019.pdf", "sayfa": ["486"]}]}
{"name": "Samsun’daki sel mağdurlarına yapılacak yardıma ve SHÇEK’de barınan bir öğrencinin durumuna ilişkin Başbakandan sorusu ve Devlet Bakanı Nimet Çubukçu’nun cevabı (7/102)", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d23/c004/tbmm23004019.pdf", "sayfa": ["543:545"]}]}
{"name": "Sosyal yardımlaşma ve dayanışma vakıflarına ilişkin sorusu ve Devlet Bakanı ve Başbakan Yardımcısı Hayati Yazıcı’nın cevabı (7/378)", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d23/c004/tbmm23004019.pdf", "sayfa": ["666:671"]}]}
{"name": "Bir müsteşar yardımcısı vekiline ilişkin sorusu ve Millî Eğitim Bakanı Hüseyin Çelik’in cevabı (7/400)", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d23/c004/tbmm23004019.pdf", "sayfa": ["694"]}]}
{"name": "Memurlara yapılan kira yardımının artırılıp artırılmayacağına ilişkin Maliye Bakanından sözlü soru önergesi ve Çevre Bakanı İmdat Sütlüoğlu'nun cevabı münasebetiyle", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d22/c003/tbmm22003027.pdf", "sayfa": ["594"]}]}
{"name": "Diyarbakır Milletvekili Muhsin Koçyiğit'in, memurlara yapılan kira yardımının artırılıp artırılmayacağına ilişkin Maliye Bakanından sözlü soru önergesi münasebetiyle", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d22/c003/tbmm22003027.pdf", "sayfa": ["593:594"]}]}
{"name": "Kocaeli Milletvekili Salih Gün'ün, belediyelere, içerisinde bulundukları malî sıkıntıların giderilebilmesi için yardım yapılması gerektiğine ilişkin gündemdışı konuşması dolayısıyla", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d22/c004/tbmm22004029.pdf", "sayfa": ["9:10"]}]}
{"name": "Belediyelere, içerisinde bulundukları malî sıkıntıların giderilebilmesi için yardım yapılması gerektiğine ilişkin", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d22/c004/tbmm22004029.pdf", "sayfa": ["7:9"]}]}
{"name": "CHP’li belediyelerin Alman vakıflarından kredi alarak terör örgütüne yardım ettikleri iddiasında bulunduğu hâlde bunu ispatlamadığı ve böylelikle üstlendiği görevi yerine getirmediği iddiasıyla Başbakan Recep Tayyip Erdoğan hakkında gensoru açılmasına ilişkin önergenin (11/4) ön görüşmeleri münasebetiyle", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d24/c005/tbmm24005024.pdf", "sayfa": ["174:178"]}]}
{"name": "Çevre Kirliliğini Önleme Fonundan Bursa'daki bazı köylere yapılan yardımlara İlişkin sorusu ve Çevre Bakanı Fevzi Aytekin'in cevabı (7/48)", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d21/c006/tbmm21006032.pdf", "sayfa": ["233:234"]}]}
{"name": "Şanlıurfa ilindeki belediyelere ve İl Özel İdaresine yapılan yardımlara İlişkin sorusu ve Maliye Bakanı Sümer Oral'ın cevabı (7/98)", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d21/c006/tbmm21006032.pdf", "sayfa": ["249"]}]}
{"name": "İzmir'in bazı ilçelerinde tabiî afetten zarar gören çiftçilere yapılacak yardıma ilişkin sorusu ve Tarım ve Köyişleri Bakanı Sami Güçlü'nün cevabı (7/125)", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d22/c004/tbmm22004030.pdf", "sayfa": ["301:304"]}]}
{"name": "Şırnak’ta sel mağdurlarına yapılacak yardıma ilişkin sorusu ve Bayındırlık ve İskân Bakanı Faruk Nafız Özak’ın cevabı (7/431)", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d23/c005/tbmm23005022.pdf", "sayfa": ["276:281"]}]}
{"name": "AB katılım öncesi mali yardım fonlarından bazı illerin yararlanamadığı iddiasına ilişkin sorusu ve Devlet Bakanı ve Başbakan Yardımcısı Nazım Ekren’in cevabı (7/346)", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d23/c005/tbmm23005022.pdf", "sayfa": ["227:231"]}]}
{"name": "Ankara Milletvekili Cevdet Erdöl’ün, Somali ve diğer Afrika ülkeleriyle ilişkilerimize ve yapılan yardım seferberliğine ilişkin gündem dışı konuşması dolayısıyla", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d24/c002/tbmm24002003.pdf", "sayfa": ["92:96"]}]}
{"name": "CHP’li belediyelerin Alman vakıflarından kredi alarak terör örgütüne yardım ettikleri iddiasında bulunduğu hâlde bunu ispatlamadığı ve böylelikle üstlendiği görevi yerine getirmediği iddiasıyla Başbakan Recep Tayyip Erdoğan hakkında gensoru açılmasına ilişkin önergenin (11/4) ön görüşmeleri münasebetiyle", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d24/c005/tbmm24005024.pdf", "sayfa": ["203:211"]}]}
{"name": "Sosyal yardım yapan vakıf ve derneklere uygulanan vergi muafiyetine ilişkin sorusu ve Maliye Bakanı Kemal Unakıtan’ın cevabı (7/484)", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d23/c005/tbmm23005024.pdf", "sayfa": ["538:539"]}]}
{"name": "Başbakanın 1 Temmuz Cuma günü 10 bin tonluk insani yardımın Mersin Limanı'ndan Filistin'e törenle gönderileceği ifadelerine ve halkın, Gazze ablukasının kalkmadığının, tam tersine tescillendiğinin farkında olduğuna ilişkin açıklaması", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d26/c020/tbmm26020108.pdf", "sayfa": ["369:370"]}]}
{"name": "Yeni atanan bakan yardımcılarının yetki, görev ve sorumluluklarının belirlenmesine ilişkin açıklaması", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d24/c004/tbmm24004019.pdf", "sayfa": ["532"]}]}
{"name": "Konya'daki belediyelere yapılan yardımlara ilişkin sorusu ve içişleri Bakanı Ülkü Güney'in cevabı (7/497)", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d20/c004/tbmm20004045.pdf", "sayfa": ["686"]}]}
{"name": "Kırıkkale'deki belediyelere yapılan yardımlara ilişkin sorusu ve Malîye Bakanı Lutfullah Kayalar' in cevabı (7/507)", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d20/c004/tbmm20004045.pdf", "sayfa": ["687"]}]}
{"name": "Belediyelere yapılan yardımlara ilişkin sorusu ve Malîye Bakanı Lutfullah Kayalar'ın cevabı (7/456)", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d20/c004/tbmm20004045.pdf", "sayfa": ["685:686"]}]}
{"name": "Konya'da bazı belediyelere partizanca yardım yapıldığı iddiasına ilişkin sorusu ve Malîye Bakanı Lutfullah Kayalar'ın cevabı (7/443)", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d20/c004/tbmm20004045.pdf", "sayfa": ["684"]}]}
{"name": "CHP’li belediyelerin Alman vakıflarından kredi alarak terör örgütüne yardım ettikleri iddiasında bulunduğu hâlde bunu ispatlamadığı ve böylelikle üstlendiği görevi yerine getirmediği iddiasıyla Başbakan Recep Tayyip Erdoğan hakkında gensoru açılmasına ilişkin önergenin (11/4) ön görüşmeleri münasebetiyle", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d24/c005/tbmm24005024.pdf", "sayfa": ["189:197"]}]}
{"name": "Doğu ve Güneydoğuda yurttaşlanmıza göç nedeniyle yapılan nakdî yardımlara ilişkin sorusu ve Devlet Bakanı Abdülkadir Aksu'nun cevabı (7/433)", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d20/c005/tbmm20005048.pdf", "sayfa": ["92:93"]}]}
{"name": "Bursa'da Millî Eğitim Müdürlüğüne bağlı bine yakın müdür, müdür başyardımcısı ve müdür yardımcısının alenen kıyıma uğratıldığına ilişkin açıklaması", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d26/c004/tbmm26004034.pdf", "sayfa": ["670"]}]}
{"name": "Cemevleri yapımı için bütçeden yardım yapıldığı iddiasına ilişkin sorusu ve Devlet Bakanı Cemil Çiçek'in yazılı cevabı (7/475)", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d20/c005/tbmm20005052.pdf", "sayfa": ["500:501"]}]}
{"name": "Bakanlıkça belediyelere yapılan yardımlara ilişkin sorusu ve Malîye Bakanı Lutfullah Kayalar'ın cevabı (7/674)", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d20/c005/tbmm20005052.pdf", "sayfa": ["506"]}]}
{"name": "Balıkesir-Şamlı Beldesi ve Halkapınar Köyünde meydana gelen yangın afetinde zarar gören çiftçilere yapılacak yardımlara İlişkin sorusu ve Tarım ve Köyişleri Bakanı Hüsnü Yusuf Gökalp'in cevabı (7/278)", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d21/c008/tbmm21008043.pdf", "sayfa": ["366:367"]}]}
{"name": "Tokat İli Turhal, Pazar ve Artova İlçelerinde meydana gelen dolu afetinden zarar gören Çiftçilere yapılacak yardımlara ilişkin sorusu ve Tarım ve Köyişleri Bakanı Hüsnü Yusuf Gökalp'in cevabı (7/298)", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d21/c008/tbmm21008045.pdf", "sayfa": ["521:523"]}]}
{"name": "Konya'dakı belediyelere yapılan yardımlara ilişkin sorusu ve İçişleri Bakanı Ülkü Güney'in cevabı (7/496)", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d20/c006/tbmm20006056.pdf", "sayfa": ["99:100"]}]}
{"name": "Amerika Temsilciler Meclisinde ekonomik yardım konusunda alınan karara TBMM'nin gösterdiği tepkiye ilişkin siyasî parti grup temsilcilerinin müşterek bildirisi", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d20/c006/tbmm20006059.pdf", "sayfa": ["363"]}]}
{"name": "Amerika Temsilciler Meclisinde ekonomik yardım konusunda alınan karara ilişkin", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d20/c006/tbmm20006059.pdf", "sayfa": ["361:363"]}]}
{"name": "AB’nin mali yardım aracı fonlarının kullanımına ilişkin Başbakandan sorusu ve Dışişleri Bakanı Ali Babacan’ın cevabı (7/570)", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d23/c009/tbmm23009036.pdf", "sayfa": ["340:342"]}]}
{"name": "CHP’li belediyelerin Alman vakıflarından kredi alarak terör örgütüne yardım ettikleri iddiasında bulunduğu hâlde bunu ispatlamadığı ve böylelikle üstlendiği görevi yerine getirmediği iddiasıyla Başbakan Recep Tayyip Erdoğan hakkında gensoru açılmasına ilişkin önergenin (11/4) ön görüşmeleri münasebetiyle", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d24/c005/tbmm24005024.pdf", "sayfa": ["182:186"]}]}
{"name": "Belediyelere yapılan yardımlara ilişkin sorusu ve İçişleri Bakanı Ülkü Güney'ın cevabı (7/487)", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d20/c006/tbmm20006062.pdf", "sayfa": ["616:617"]}]}
{"name": "Belediyelere yapılan yardımlara ilişkin sorusu ve İçişleri Bakanı Ülkü Güney'ın cevabı (7/478)", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d20/c007/tbmm20007063.pdf", "sayfa": ["73:74"]}]}
{"name": "Balıkesir İli Merkez Halkapınar Köyü ile Şamlı Beldesi civarında çıkan yangında zarar gören çiftçilere yardım yapılıp yapılmayacağına İlişkin sorusu ve Devlet Bakanı Hasan Gemici'nin cevabı (7/330)", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d21/c011/tbmm21011053.pdf", "sayfa": ["16:17"]}]}
{"name": "Samsun İli Vezirköprü ilçesinde yaşanan dolu afetinde zarar gören çiftçilere yardım yapılıp yapılmayacağına ilişkin sorusu ve Tarım ve Köyişleri Bakanı Hüsnü Yusuf Gökalp'in cevabı (7/332)", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d21/c011/tbmm21011054.pdf", "sayfa": ["66:68"]}]}
{"name": "SATAŞMALARA İLİŞKİN KONUŞMALAR VE AÇIKLAMALAR-Sağlık Bakanı Osman Durmuş'un, DYP Genel Başkanı İstanbul Milletvekili Tansu Çiller'in, konuşmasında, yurt dışından teklif edilen bazı tıbbî yardımların kabul edilmediği ifadelerine İlişkin", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d21/c011/tbmm21011055.pdf", "sayfa": ["116:117"]}]}
{"name": "Bayır Bucak bölgesinde birçok köyün Rus birlikleri tarafından işgal edildiğine ve Hükûmetin Türkmenlere gerekli yardımları yapmasını talep ettiğine ilişkin açıklaması", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d26/c019/tbmm26019103.pdf", "sayfa": ["565"]}]}
{"name": "Memurlara verilen kıra yardımının yeterli düzeye çıkarılmasına ilişkin sorusu ve Malîye Bakanı Lutfrllah Kayalar'in cevabı (7/846)", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d20/c007/tbmm20007065.pdf", "sayfa": ["278"]}]}
{"name": "Mahallî idarelere yapılacak yardım ve ödemeler tertibinden Kocaeli belediyelerine ayrılan miktara ilişkin sorusu ve Malîye Bakanı Lutfullah Kayalar'ın cevabı (7/927)", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d20/c007/tbmm20007066.pdf", "sayfa": ["347"]}]}
{"name": "DYP Genel Başkanı İstanbul Milletvekili Tansu Çiller'in, konuşmasında, yurt dışından teklif edilen bazı tıbbî yardımların kabul edilmediği ifadelerine İlişkin", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d21/c011/tbmm21011055.pdf", "sayfa": ["116:117"]}]}
{"name": "Adıyaman Kahta İlçesi Belediyesine 1999 Yılı Bütçesinden yardım yapılıp yapılmadığına ilişkin sorusu ve Maliye Bakanı Sümer Oral'ın cevabı (7/399)", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d21/c011/tbmm21011056.pdf", "sayfa": ["470:471"]}]}
{"name": "Necmettin Erbakan'ın abdest almasına yardımcı olanların Devlet memuru olup olmadıklarına ilişkin sorusu ve İçişleri Bakanı Ülkü Güney'in cevabı (7/828)", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d20/c007/tbmm20007068.pdf", "sayfa": ["422:423"]}]}
{"name": "AÇBA Sait (Afyon)*Depremden sonra Dinar ve köylerine yapılan yardımlara ilişkin sorusu ve Bayındırlık ve İskân Bakanı Mehmet Keçecilerin cevabı (7/868)", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d20/c007/tbmm20007069.pdf", "sayfa": ["488:489"]}]}
{"name": "Sosyal Hizmetler ve Çocuk Esirgeme Kurumu tarafından bir aileye yardım yapılıp yapılmadığına ilişkin sorusu ve Devlet Bakanı İmren Aykut'un cevabı (7/829)", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d20/c007/tbmm20007069.pdf", "sayfa": ["470:471"]}]}
{"name": "Somali ve diğer Afrika ülkeleriyle ilişkilerimize ve yapılan yardım seferberliğine ilişkin gündem dışı konuşması ", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d24/c002/tbmm24002003.pdf", "sayfa": ["90:91"]}]}
{"name": "Iğdır Milletvekili Sinan Oğan’ın, Ahıska Türklerinin ana vatanları olan Gürcistan’a dönmeleri konusunda yardımcı olunmasına, Mersin Milletvekili Mehmet Şandır’ın, Ahıska Türklerinin sorunlarına çözüm bulunmasına ve diyabet hastalığının araştırılarak alınması gereken tedbirlere, Muş Milletvekili Sırrı Sakık’ın, Van, Bitlis, Muş ve çevresinde yaşanan kötü hava şartları nedeniyle pancar üreticilerinin mağduriyetlerinin giderilmesine, Erzincan Milletvekili Muharrem Işık’ın, ülkemizde nişasta bazlı şeker üretiminin her yıl kotasının arttırılmasının sağlığa ve çevreye verdiği zararlara ve mısır ithalatında kazanç sağlayan firmaların araştırılmasına, Mersin Milletvekili Aytuğ Atıcı’nın, diyabet konusunda Sağlık Bakanı yerine niçin Orman ve Su İşleri Bakanının açıklama yaptığına ve ülkemizde geçim sıkıntısı çeken vatandaşların gönüllü kobay olarak bilimsel araştırmalarda kullanıldıkları iddialarına, Osmaniye Milletvekili Hasan Hüseyin Türkoğlu’nun, terör örgütü ile Türk devleti arasında arabuluculuk talebinde bulunulduğuna dair basına yansıyan haberlere ve Hatay Milletvekili Refik Eryılmaz’ın, terör örgütüne verildiği öne sürülen desteğin ülkemizin ulusal çıkarlarını ve güvenliğini tehdit ettiğine, ilişkin açıklamaları dolayısıyla", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d24/c004/tbmm24004020.pdf", "sayfa": ["696:697"]}]}
{"name": "Van ilinde meydana gelen depremlerde, arama ve kurtarma çalışmaları, yardımların ulaştırılması, hasar tespiti ve süreçteki diğer hizmetlerin yerine getirilmesinde etkin koordinasyon sağlayamadığı iddiasıyla Başbakan Yardımcısı Beşir Atalay hakkında gensoru açılmasına ilişkin önergenin (11/6) ön görüşmeleri münasebetiyle", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d24/c005/tbmm24005027.pdf", "sayfa": ["749:753"]}]}
{"name": "Hâkimler ve Savcılar Yüksek Kurulu ve Yargıtay üyeleriyle ilgili iddialara ve Van depreminde mağdur olan depremzedelere yeterli yardımların yapılmadığına ilişkin açıklaması", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d24/c004/tbmm24004019.pdf", "sayfa": ["536"]}]}
{"name": "Van ilinde meydana gelen depremlerde, arama ve kurtarma çalışmaları, yardımların ulaştırılması, hasar tespiti ve süreçteki diğer hizmetlerin yerine getirilmesinde etkin koordinasyon sağlayamadığı iddiasıyla Başbakan Yardımcısı Beşir Atalay hakkında gensoru açılmasına ilişkin önergenin (11/6) ön görüşmeleri münasebetiyle", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d24/c005/tbmm24005027.pdf", "sayfa": ["740:744"]}]}
{"name": "Diyanet İşleri Başkanlığına bağlı olmayan ibadethaneler ve Kur’an kursları ile yardım toplanmasına ilişkin Başbakandan sorusu ve Devlet Bakanı Mustafa Said Yazıcıoğlu’nun cevabı (7/1095)", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d23/c012/tbmm23012048.pdf", "sayfa": ["106:109"]}]}
{"name": "Antalya Milletvekili Tayfur Süner’in, Akseki’deki çok programlı liseye (6/148), Mersin Milletvekili İsa Gök’ün, bir okuldaki öğrencilere oruç tutmaya yönelik baskı uygulandığı iddialarına (6/151), Yalova Milletvekili Muharrem İnce’nin, Bir müsteşar yardımcısına tahsis edilen odaya (6/160), Bir konuşmasında kullandığı ifadeye (6/175), Kütahya Milletvekili Alim Işık’ın, Dumlupınar Üniversitesi bünyesinde Tıp Fakültesi kurulmasına (6/174), Ordu Milletvekili Rıdvan Yalçın’ın, öğrencilerin belli faaliyetlere katılımının yasaklanmasına (6/189), Ardahan Milletvekili Ensar Öğüt’ün Bir köy okulunun tamirat ve lojman ihtiyacına (6/194), Bazı köy okullarının sorunlarına (6/206, 207, 208, 209, 210, 211, 212, 213, 214, 216, 217, 218, 219, 220, 223, 227), Bir köy okulunun lojman ihtiyacına (6/215), Bazı köy okullarının bakım ve onarımlarına (6/221, 222), Bazı köy okullarının öğretmen ihtiyaçlarına (6/224, 226) ve Bir köy okulu lojmanının onarımına (6/225) ve İstanbul Milletvekili Necla Arat’ın İstanbul’da yabancı bir üniversitenin yerleşke açtığı haberlerine (6/200), Bir kongrede açıklanan görüşe tepki verilip verilmediğine (6/203) ve Camiler Haftası nedeniyle yayınlandığı iddia edilen genelgeye (6/202) ilişkin sözlü soru önergeleri münasebetiyle", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d23/c012/tbmm23012049.pdf", "sayfa": ["206:211", "212:213"]}]}
{"name": "Gezi olaylarının kitleselleşmesinden telaşlanan zamanın Hükûmetinin birtakım terör örgütlerinden ve PKK'nın İmralı'daki elebaşından yardım istediğine ilişkin açıklaması", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d26/c018/tbmm26018096.pdf", "sayfa": ["305"]}]}
{"name": "Maliye Bakanlığının, şeffaflık ilkesi gereğince belediyelere yaptığı yardımları açıklaması gerektiğine ve Türkiye Cumhuriyeti'nin kuruluş yıllarında da ilkokullarda ders kitaplarının parasız verildiğine ilişkin açıklaması", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d26/c010/tbmm26010053.pdf", "sayfa": ["463"]}]}
{"name": "Anadolu Liselerinde görev yapan müdür ve müdür yardımcılarının orta öğrenimlerine ilişkin sorusu ve Millî Eğitim Bakanı Mehmet Sağlam'ın cevabi (7/994)", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d20/c009/tbmm20009084.pdf", "sayfa": ["212"]}]}
{"name": "Deprem felâketi nedeniyle yapılan uluslararası yardımlardan gümrük vergisi alınıp alınmadığına ilişkin sorusu ve Devlet Bakanı Tunca Toskaym cevabı (7/507)", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d21/c013/tbmm21013001.pdf", "sayfa": ["229:231"]}]}
{"name": "Çevre Kirliliği Fonundan belediyele gönderilen şartlı yardımların gen çekilmesinin nedenine ilişkin sorusu ve Çevre Bakanı M. Ziyattin Tokar'ın cevabı (7/1211)", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d20/c010/tbmm20010088.pdf", "sayfa": ["177:178"]}]}
{"name": "Adana’da Özbucak Fabrikasının iflasından dolayı mağdur olan vatandaşlara yardım noktasında duyarlı olunması gerektiğine ilişkin açıklaması", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d24/c023/tbmm24023119.pdf", "sayfa": ["244"]}]}
{"name": "Ardahan Milletvekili Ensar Öğüt’ün, bazı sınır kapılarının dinî bayramlarda açılmasına (6/176), Gaziantep Milletvekili Hasan Özdemir’in, bazı belediye başkanları hakkında bir işlem yapılıp yapılmadığına (6/184), Ordu Milletvekili Rıdvan Yalçın’ın, Belediyelerin sosyal yardımlarına (6/191), Belediyelerin sosyal yardım yaptığı kişilere (6/192) ve Uyuşturucu kaçakçılığı kapsamında dağıtılan ikramiyeye (6/340), Tokat Milletvekili Reşat Doğru’nun, Bir köy ilköğretim okulunun yapım ihalesine (6/193) ve Niksar Belediyesinin arsa ihalelerine yönelik iddialara (6/355), İstanbul Milletvekili Mehmet Ufuk Uras’ın, Bandırma’da bazı cadde isimlerinin değiştirilmesine (6/240), Bursa Milletvekili İsmet Büyükataman’ın, Celal Bayar anıt mezarına (6/253), Tunceli Milletvekili Kamer Genç’in, polis müdahalesiyle meydana geldiği iddia edilen bazı ölüm olaylarına (6/261), Aksaray Milletvekili Osman Ertuğrul’un, Demirci kasabasının Aksaray’a bağlanmasına (6/267), Antalya Milletvekili Tayfur Süner’in, Antalya’nın katı atık ayrıştırma tesisi ihtiyacına (6/288), Antalya’daki bir sanayi sitesinin güvenliğine (6/289) ve Ücretsiz dağıtılan kömürlerin hava kirliliğine yol açtığı iddialarına (6/293), Antalya Milletvekili Hüsnü Çöllü’nün, Antalya toptancı halindeki iş yerlerinin kira artışına (6/304), Karaman Milletvekili Hasan Çalış’ın, Ülkemiz üzerinden yapılan insan kaçakçılığına (6/305) ve Yurtiçi uçuşlardaki genel bilgi toplama uygulamasına (6/319) ve Çankırı Milletvekili Ahmet Bukan’ın, Çankırı Belediye Başkanı hakkındaki soruşturma iznine (6/307), ilişkin sözlü soru önergeleri münasebetiyle", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d23/c013/tbmm23013055.pdf", "sayfa": ["182:192"]}]}
{"name": "Belediyelerin sosyal yardımlarına (6/191), Belediyelerin sosyal yardım yaptığı kişilere (6/192) ve Uyuşturucu kaçakçılığı kapsamında dağıtılan ikramiyeye (6/340) ilişkin İçişleri Bakanından sözlü soru önergeleri münasebetiyle", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d23/c013/tbmm23013055.pdf", "sayfa": ["192:193"]}]}
{"name": "Sivas İli ve Konya İline bağlı belediyelere yapılan yardımların miktarlarına ilişkin sorusu ve Malîye Bakanı Abdüllatif Şener'in cevabi (7/1066)", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d20/c010/tbmm20010088.pdf", "sayfa": ["132"]}]}
{"name": "Edirne Defterdarlığında yardımcı hizmetler sınıfında çalışanların genel idare hizmetler sınıfına atamalarının yapılmasına ilişkin sorusu ve Malîye Bakanı Abdullatif Şener'in cevabı (7/1264)", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d20/c010/tbmm20010088.pdf", "sayfa": ["146:147"]}]}
{"name": "Tabiî afetler nedeniyle ürün kaybına uğrayan çiftçilere tohumluk yardımı yapılmasına ve patates üreticilerinin sorunları ile alınması gereken önlemlere ilişkin", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d21/c013/tbmm21013004.pdf", "sayfa": ["421:422"]}]}
{"name": "Nevşehir Milletvekili Mehmet Elkatmış'in, tabiî afetler nedeniyle ürün kaybına uğrayan çiftçilere tohumluk yardımı yapılmasına ve patates üreticilerinin sorunları ile alınması gereken önlemlere ilişkin gündemdışı konuşması dolayısıyla", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d21/c013/tbmm21013004.pdf", "sayfa": ["430:437"]}]}
{"name": "Başkanlık Divanındaki Kâtip Üyelerin yoklama yapılması sırasında Başkana yardımcı olmaları gerektiğine ilişkin açıklaması", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d24/c011/tbmm24011051.pdf", "sayfa": ["361"]}]}
{"name": "Şehit ailelerine yapılacak yardımlara ilişkin sorusu ve İçişleri Bakanı Mehmet Ağar'ın cevabı (7/1223)", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d20/c010/tbmm20010090.pdf", "sayfa": ["454:455"]}]}
{"name": "Ve 32 milletvekilinin, konut edindirme yardımı hesapları konusunda Meclis araştırması açılmasına ilişkin önergesi (10/79)", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d22/c014/tbmm22014080.pdf", "sayfa": ["554:557"]}]}
{"name": "Tokat Milletvekili Reşat Doğru’nun, Zile Anadolu Öğretmen Lisesine ayrılan ödeneğe ve bina yapımına (6/237), Gaziantep Milletvekili Yaşar Ağyüz’ün, yönetici ve öğretmen atamalarına (6/241), Tunceli Milletvekili Kamer Genç’in, okullarda dağıtılan kitaplara (6/263), Antalya Milletvekili Tayfur Süner’in, Amasya’daki bir lisede bazı öğrencilere baskı uygulandığı iddialarına (6/285) ve Kaş İlköğretim Okulu inşaatına (6/331), Antalya Milletvekili Hüsnü Çöllü’nün, Antalya’nın bazı ilçelerinde ÖSYM sınav merkezi açılıp açılmayacağına (6/301), Balıkesir Milletvekili Ergün Aydoğan’ın, bir okul müdürü hakkındaki iddiaya (6/303), Karaman Milletvekili Hasan Çalış’ın, Sarıveliler ilçesine yeni bir lise yapılmasına (6/306) ve İlköğretim Kurumları Yönetmeliğinde yapılan bir değişikliğe (6/349), Bursa Milletvekili İsmet Büyükataman’ın, Terör mağduru öğretmenlere (6/308), Yüksek lisans ve doktora yapan öğretmenlere (6/334) ve Okullardaki temizlik ve güvenlik görevlilerine (6/356), Ordu Milletvekili Rıdvan Yalçın’ın, öğrenci yurtlarına (6/344) ve İzmir Milletvekili Şenol Bal’ın, İzmir’de depremde yıkılma riski taşıyan okullara (6/358) ve Bir yardımcı kaynak kitaptaki Türkiye haritasına (6/387) ilişkin sözlü soru önergeleri münasebetiyle", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d23/c013/tbmm23013058.pdf", "sayfa": ["576:581", "582:583"]}]}
{"name": "Kırgızistan’a deprem yardımı yapılıp yapılmadığına ilişkin sorusu ve Devlet Bakanı Mustafa Said Yazıcıoğlu’nun cevabı (7/1598)", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d23/c013/tbmm23013058.pdf", "sayfa": ["644:645"]}]}
{"name": "Yalova’daki sosyal yardımlaşma ve dayanışma mütevelli heyetlerinin üye seçimine ilişkin sorusu ve Devlet Bakanı ve Başbakan Yardımcısı Hayati Yazıcı’nın cevabı (7/1631)", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d23/c013/tbmm23013059.pdf", "sayfa": ["862:867"]}]}
{"name": "Simav depreminde konutları yıkılan vatandaşlara verile-cek şehir merkezine uzak TOKİ konutları yerine kendi arsalarına ev yaptırma hususunda avantaj sağlanıp sağlanamayacağı ve orta hasarlı binalar için yapılan yardımın artırılmasına ilişkin açıklaması", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d24/c002/tbmm24002006.pdf", "sayfa": ["303"]}]}
{"name": "Adana’daki bazı atık su ve arıtma tesislerinin yapımına teknik ve mali yardım yapılıp yapılmadığına (7/1477) ve Çevreye duyarlı sanayi kuruluşlarına (7/1622) ilişkin soruları ve Çevre ve Orman Bakanı Veysel Eroğlu’nun cevabı", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d23/c014/tbmm23014063.pdf", "sayfa": ["363:368"]}]}
{"name": "Deprem bölgesindeki depremzedelere yardımda bulunan bazı vakıfların faaliyetlerine son verildiği iddialarına ilişkin sorusu ve İçişleri Bakanı Sadettin Tantan'ın cevabı (7/558)", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d21/c015/tbmm21015014.pdf", "sayfa": ["277:278"]}]}
{"name": "Kızılay'ın ve THK'nun mal varlıkları, personel sayısı ve felâketzedelere yaptıkları yardımlara ilişkin sorusu ve İçişleri Bakanı Sadettin Tantan'ın cevabı (7/517)", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d21/c015/tbmm21015014.pdf", "sayfa": ["264:265"]}]}
{"name": "Doğu ve Güneydoğu'dan göç edenlere yapılması düşünüleri yardımlara ilişkin sorusu ve İçişleri Bakanı Mehmet Ağar'in cevabı (7/1122)", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d20/c011/tbmm20011001.pdf", "sayfa": ["78"]}]}
{"name": "CHP’li belediyelerin Alman vakıflarından kredi alarak terör örgütüne yardım ettikleri iddiasında bulunduğu hâlde bunu ispatlamadığı ve böylelikle üstlendiği görevi yerine getirmediği iddiasıyla Başbakan Recep Tayyip Erdoğan hakkında gensoru açılmasına ilişkin önergenin (11/4) ön görüşmeleri münasebetiyle", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d24/c005/tbmm24005024.pdf", "sayfa": ["170:174"]}]}
{"name": "Deprem nedeniyle yapılan yardım kampanyalarına ilişkin açıklaması", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d24/c003/tbmm24003011.pdf", "sayfa": ["40"]}]}
{"name": "Bir televizyon kanalının şehit yakınları ve gazilere yardım kampanyasına ilişkin sorusu ve Millî Savunma Bakanı M. Vecdi Gönül’ün cevabı (7/1529)", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d23/c014/tbmm23014064.pdf", "sayfa": ["482:484"]}]}
{"name": "Dernek, vakıf ve benzeri kuruluşlara yapılan yardımlara ilişkin sorusu ve Kültür Bakanı İsmail Kahraman'ın cevabı (7/1242)", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d20/c011/tbmm20011001.pdf", "sayfa": ["157:159"]}]}
{"name": "Şehit ve Gazi aileleri için yapılması düşünüleri yardımlara ilişkin sorusu ve Millî Savunma Bakanı Turhan Tayan'ın cevabı (7/1194)", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d20/c011/tbmm20011001.pdf", "sayfa": ["116:118"]}]}
{"name": "Destekleme Fonundan 1995 yılı içinde illere yapılan yardımlara ilişkin sorusu ve Maliye Bakanı Abdüllatif Şener'in cevabı (6/129)", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d20/c011/tbmm20011004.pdf", "sayfa": ["281"]}]}
{"name": "Deprem bölgesinde hasar gören binalara Ölen, yaralanan ya da kaybolan kişilere ve yapılan yardımlara, ilişkin sorulan ve Bayındırlık ve İskân Bakanı Koray Aydın'ın cevabı (7/562)", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d21/c016/tbmm21016016.pdf", "sayfa": ["83:95"]}]}
{"name": "Eskişehir Milletvekili Hanifi Demirkol'un, Destekleme Fonundan 1995 yılı içinde illere yapılan yardımlara ilişkin sorusu münasebetiyle", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d20/c011/tbmm20011004.pdf", "sayfa": ["281"]}]}
{"name": "Deprem felaketzedeleri için gönderilen dış kaynaklı yardım paralarının maaş ödemelerinde kullanıldığı iddialarına ilişkin sorusu ve Devlet Bakanı Recep Ünal'ın cevabı (7/713)", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d21/c016/tbmm21016018.pdf", "sayfa": ["298:303"]}]}
{"name": "Bursa-Orhaneli köylerine Sosyal Yardımlaşma ve Dayanışmayı Teşvik Fonundan yapılan yardımlara, Bursa-Keles köylerine Sosyal Yardımlaşma ve Dayanışmayı Teşvik Fonundan yapılan yardımlara, Bursa-Harmancık köylerine Sosyal Yardımlaşma ve Dayanışmayı Teşvik Fonundan yapılan yardımlara ilişkin soruları ve Devlet Bakanı Beşir Atalay'ın cevabı (7/590,591,592,593)", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d22/c017/tbmm22017091.pdf", "sayfa": ["257:261"]}]}
{"name": "Sosyal Yardımlaşma ve Dayanışmayı Teşvik Fonundan İstanbul İlinde dağıtılan yardımların miktarına ilişkin sorusu ve Devlet Bakanı Beşir Atalay'ın cevabı (7/547)", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d22/c017/tbmm22017091.pdf", "sayfa": ["245:247"]}]}
{"name": "Başbakanın “Yirmi dört saat geç kaldık, başarısız ol-duk” ve “Gösterilerde hemen organize olan BDP’liler afet günü yardımlarında nerede?” şeklindeki ifadelerine ilişkin açıklaması ", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d24/c003/tbmm24003012.pdf", "sayfa": ["165", "166"]}]}
{"name": "CHP’li belediyelerin Alman vakıflarından kredi alarak terör örgütüne yardım ettikleri iddiasında bulunduğu hâlde bunu ispatlamadığı ve böylelikle üstlendiği görevi yerine getirmediği iddiasıyla Başbakan Recep Tayyip Erdoğan hakkında gensoru açılmasına ilişkin önergenin (11/4) ön görüşmeleri münasebetiyle", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d24/c005/tbmm24005024.pdf", "sayfa": ["186"]}]}
{"name": "Başbakanın 1 Temmuz Cuma günü 10 bin tonluk insani yardımın Mersin Limanı'ndan Filistin'e törenle gönderileceği ifadelerine ve halkın, Gazze ablukasının kalkmadığının, tam tersine tescillendiğinin farkında olduğuna ilişkin açıklaması", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d26/c020/tbmm26020108.pdf", "sayfa": ["369:370"]}]}
{"name": "Deprem felâketzedeleri için gönderilen dış kaynaklı yardım paralarının maaş ödemelerinde kullanıldığı iddialarına ilişkin sorusu ve Devlet Bakanı Recep Önal'ın cevabı (7/714)", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d21/c016/tbmm21016019.pdf", "sayfa": ["405"]}]}
{"name": "Sivil savunma hizmetlerine ve yardım çalışmaları engellenen İHD ve Mazlum-Der'e ilişkin sorusu ve İçişleri Bakanı Sadettin Tantan'ın cevabı (7/741)", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d21/c016/tbmm21016019.pdf", "sayfa": ["409:411"]}]}
{"name": "Kocaeli deprem bölgesinde bazı vakıfların yardım faaliyetlerine son verildiği iddialarına ilişkin sorusu ve İçişleri Bakanı Sadettin Tantan'ın cevabi) 7/561)", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d21/c016/tbmm21016019.pdf", "sayfa": ["367:368"]}]}
{"name": "Ve 24 milletvekilinin, Marmara depremi sonrasında yapılan yardımlar ve kamu ihaleleriyle ilgili iddiaların araştırılması amacıyla Meclis araştırması açılmasına ilişkin önergesi (10/108)", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d22/c018/tbmm22018093.pdf", "sayfa": ["13:16"]}]}
{"name": "Van ilinde meydana gelen depremin ilk yirmi dört saati içinde Cizre Belediyesince yapılan yardımlara ilişkin açıklaması", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d24/c003/tbmm24003013.pdf", "sayfa": ["213"]}]}
{"name": "Van ilinde meydana gelen depremlerde, arama ve kurtarma çalışmaları, yardımların ulaştırılması, hasar tespiti ve süreçteki diğer hizmetlerin yerine getirilmesinde etkin koordinasyon sağlayamadığı iddiasıyla Başbakan Yardımcısı Beşir Atalay hakkında gensoru açılmasına ilişkin önergenin (11/6) ön görüşmeleri münasebetiyle", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d24/c005/tbmm24005027.pdf", "sayfa": ["736:739"]}]}
{"name": "Van ve Erciş’te meydana gelen deprem için yardım toplayan BDP’li belediyelere baskı yapıldığına ilişkin açıklaması", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d24/c003/tbmm24003012.pdf", "sayfa": ["175:176"]}]}
{"name": "Bursa'da Millî Eğitim Müdürlüğüne bağlı bine yakın müdür, müdür başyardımcısı ve müdür yardımcısının alenen kıyıma uğratıldığına ilişkin açıklaması", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d26/c004/tbmm26004034.pdf", "sayfa": ["670"]}]}
{"name": "Belediyelere yapılan yardımlara ilişkin sorusu ve Maliye Bakanı Sümer Oral'ın cevabı (7/775)", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d21/c016/tbmm21016020.pdf", "sayfa": ["536:537"]}]}
{"name": "57. Hükümet döneminde Hatay İlindeki belediyelere yapılan yardım miktarına ilişkin sorusu ve Çevre Bakanı Fevzi Aytekin'in cevabı (7/819)", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d21/c017/tbmm21017021.pdf", "sayfa": ["88:89"]}]}
{"name": "Gaziantep'teki belediyelere yapılan nakdi yardımlara ilişkin sorusu ve Maliye Bakanı Kemal Unakıtan'ın cevabı (7/546)", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d22/c018/tbmm22018094.pdf", "sayfa": ["122"]}]}
{"name": "Sinop Milletvekili Metin Bostancıoğlu'nun, tabiî afetler ve Sinop'lu hak sahiplerine yapılması gereken yardımlara ilişkin gündemdışı konuşması dolayısıyla", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d20/c013/tbmm20013013.pdf", "sayfa": ["101:102"]}]}
{"name": "Tabiî afetler ve Sinoplu hak sahiplerine yapılması gereken yardımlara ilişkin", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d20/c013/tbmm20013013.pdf", "sayfa": ["99:101"]}]}
{"name": "Afet yardımlarına ilişkin sorusu ve Bayındırlık ve iskân Bakanı Koray Aydın'ın cevabı (7/769)", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d21/c017/tbmm21017023.pdf", "sayfa": ["403:404"]}]}
{"name": "Bingöl-Genç-Gerçekli Köyündeki terör mağduru bir şahsa yardım yapılıp yapılmadığına ilişkin sorusu ve İçişleri Bakanı Abdülkadir Aksu'nun cevabı (7/611)", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d22/c019/tbmm22019097.pdf", "sayfa": ["163:164"]}]}
{"name": "Başbakan Yardımcısı Beşir Atalay’ın, Şırnak ilinin Uludere ilçesinin sınır kesiminde yapılan hava operasyonunda 35 vatandaşımızın hayatını kaybetmesi ve açılan soruşturma ile bu vatandaşlarımızın geride kalan yakınlarına yapılacak yardımlara ilişkin Hükûmet adına açıklaması nedeniyle BDP Grubu adına konuşması", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d24/c010/tbmm24010046.pdf", "sayfa": ["219:221"]}]}
{"name": "Eğitim kurumları müdür yardımcılığı sınavındaki bazı soruların iptal edilmesine ilişkin sorusu ve Millî Eğitim Bakanı Hüseyin Çelik’in cevabı (7/1768)", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d23/c015/tbmm23015072.pdf", "sayfa": ["846:848"]}]}
{"name": "Sinop Milletvekili Metin Bostancıoğlu'nun, tabiî afetler ve Sinoplu hak sahiplerine yapılması gereken yardımlara ilişkin gündemdışı konuşması dolayısıyla", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d20/c013/tbmm20013013.pdf", "sayfa": ["101:102"]}]}
{"name": "Konya'daki belediyelere yapılan yardımlara ilişkin sorusu ve Devlet Bakanı Lütfü Esengün'ün cevabı (6/36,6/37)", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d20/c013/tbmm20013014.pdf", "sayfa": ["266"]}]}
{"name": "Başbakanlık ve bakanlıklardaki müsteşar, müsteşar yardımcısı ve genel müdür maaşlarına ilişkin sorusu ve Devlet Bakanı Lütfü Esengün'ün cevabı (7/1230)", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d20/c013/tbmm20013014.pdf", "sayfa": ["307:312"]}]}
{"name": "Belediyelere yapılan yardımlara ilişkin sorusu ve Devlet Bakanı Lütfü Esengün'ün cevabı (7/1179)", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d20/c013/tbmm20013014.pdf", "sayfa": ["299:302"]}]}
{"name": "Kırıkkale ilinde sel felaketinden zarar görenlere yapılacak yardımlara, Kırıkkale Koçubaba ve Karaahmetlı belediyelerinin sel felaketi nedeniyle afet kapsamına alınıp alınmayacağına ilişkin sorulan ve Bayındırlık ve İskân Bakanı Koray Aydın'ın cevabı (7/752,841)", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d21/c018/tbmm21018026.pdf", "sayfa": ["123:125"]}]}
{"name": "Depremzedeler için gönderilen dış kaynaklı yardımların maaş ödemelerinde kullanıldığı iddiasına ilişkin sorusu ve Devlet Bakanı Recep Önal'ın cevabı (7/749)", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d21/c018/tbmm21018026.pdf", "sayfa": ["116:123"]}]}
{"name": "Marmara depreminde zarar görenlere yapılan yardım miktarına ilişkin sorusu ve Bayındırlık ve İskân Bakanı Koray Aydın'ın cevabı (7/681)", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d21/c018/tbmm21018026.pdf", "sayfa": ["94:96"]}]}
{"name": "Depremden zarar gören il ve ilçe belediyelerine yapılacak yardımlara ilişkin sorusu ve Bayındırlık ve İskân Bakanı Koray Aydın'ın cevabı (7/711)", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d21/c018/tbmm21018026.pdf", "sayfa": ["103:105"]}]}
{"name": "Bursa Dağ Yöresindeki belediyelere yapılan yardımlara İlişkin soruları ve Çevre Bakanı Fevzi Aytekin'in cevabı (7/846)", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d21/c018/tbmm21018026.pdf", "sayfa": ["180:182"]}]}
{"name": "Konya Milletvekili Mustafa Ünaldı'nın, Konya'daki belediyelere yapılan yardımlara ilişkin Başbakandan sorusu münasebetiyle", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d20/c013/tbmm20013014.pdf", "sayfa": ["267"]}]}
{"name": "(Gaziantep)*Sivas il, ilçe ve belde belediye başkanlarına yapılan yardımlara ilişkin sorusu ve Devlet Bakanı Lütfü Esengün'ün cevabı (7/1164)", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d20/c013/tbmm20013016.pdf", "sayfa": ["486:488"]}]}
{"name": "Kuşadasında meydana gelen sel felaketinden zarar görenlere yapılacak yardımlara ve hasara uğrayan altyapı yatırımlarına ilişkin sorusu ve Devlet Bakanı Lütfü Esengün'ün cevabı (7/1346)", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d20/c013/tbmm20013017.pdf", "sayfa": ["617"]}, {"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d20/c017/tbmm20017034.pdf", "sayfa": ["173:175"]}]}
{"name": "İşitme Engelliler Futbol Milli Takımının Avrupa turnuvasına katılabilmesi için yardım yapılıp yapılmayacağına ilişkin sorusu ve Devlet Bakanı ve Başbakan Yardımcısı Mehmet Ali Şahin'in cevabı (7/738)", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d22/c020/tbmm22020103.pdf", "sayfa": ["549:550"]}]}
{"name": "Aydın Defterdarlığı Kuşadası Vergi Dairesinde görevli müdür ve müdür yardımcılarının başka bir yere yapılan tayin nedenine ilişkin sorusu ve Maliye Bakanı Abdüllatif Şener'in cevabı (7/1539)", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d20/c014/tbmm20014019.pdf", "sayfa": ["91:92"]}]}
{"name": "Ahıska Türklerinin ana vatanları olan Gürcistan’a dönmeleri konusunda yardımcı olunmasına ilişkin açıklaması", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d24/c004/tbmm24004020.pdf", "sayfa": ["693"]}]}
{"name": "Konut edindirme yardımı ödemelerine ilişkin sorusu ve Devlet Bakanı ve Başbakan Yardımcısı Nazım Ekren’in cevabı (7/2005)", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d23/c017/tbmm23017081.pdf", "sayfa": ["130:132"]}]}
{"name": "Erzincan İli Sosyal Yardımlaşma ve Dayanışma Vakfı tarafından okul ve yurtlara yapılan yardımlara ilişkin sorusu ve Devlet Bakanı ve Devlet Bakanı Vekili Ahmet Cemil Tunç'un cevabı (7/1553)", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d20/c014/tbmm20014024.pdf", "sayfa": ["459:461"]}]}
{"name": "Vakıflar Bankası müfettiş yardımcılığı sözlü sınavıyla ilgili bazı iddialara ilişkin sorusu ve Devlet Bakanı ve Başbakan Yardımcısı Mehmet Ali Şahin'in cevabı (7/806)", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d22/c022/tbmm22022106.pdf", "sayfa": ["126:128"]}]}
{"name": "Kamu personeline yapılan lojman yardımına ilişkin sorusu ve Maliye Bakanı Abdüllatif Şener'in cevabı (7/1575)", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d20/c014/tbmm20014025.pdf", "sayfa": ["567:568"]}]}
{"name": "Belediyelere yapılan yardımlara ilişkin sorusu ve Maliye Bakanı Abdüllatif Şener'in cevabı (7/1540)", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d20/c014/tbmm20014025.pdf", "sayfa": ["560:561"]}]}
{"name": "17 Ağustos depreminden sonra Başbakanlık Kriz Yönetim Merkezinde toplanan yardımlara ıtışkın sorusu ve Devlet Bakanı ve Başbakan Yardımcısı H. Hüsamettin Özkan'ın cevabı (7/898)", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d21/c020/tbmm21020036.pdf", "sayfa": ["250:312"]}]}
{"name": "Marmara depreminde zarar görenler için toplanan yardım miktarına ve dağıtım şekline ilişkin sorusu ve Devlet Bakanı ve Başbakan Yardımcısı H. Hüsamettin Özkan'ın cevabı (7/855)", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d21/c020/tbmm21020036.pdf", "sayfa": ["186:249"]}]}
{"name": "Depremzedeler için İstanbul Valiliğince başlatılan yardım kampanyasında toplanan paraya ilişkin sorusu ve İçişleri Bakanı Sadettin Tantan'ın cevabı (7/945)", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d21/c020/tbmm21020036.pdf", "sayfa": ["315:317"]}]}
{"name": "Urla ve Seferihisar'daki deprem sonrası çalışmalara ve yardımlara, İlişkin sorusu ve Bayındırlık ve İskân Bakanı Vekili ve İçişleri Bakanı Abdülkadir Aksu'nun cevabı (7/778)", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d22/c023/tbmm22023109.pdf", "sayfa": ["409:414"]}]}
{"name": "Bosna-Hersek Hükümetine yardım yapılıp yapılmadığına ilişkin sorusu ve Devlet Bakanı Lütfü Esengün'ün cevabı (7/1621)", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d20/c016/tbmm20016031.pdf", "sayfa": ["532:533"]}]}
{"name": "Bingöl depremzedelerine yapılacak yardımlara ilişkin sorusu ve Bayındırlık ve İskân Bakanı Zeki Ergezen'in cevabı (7/760)", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d22/c025/tbmm22025112.pdf", "sayfa": ["128:135"]}]}
{"name": "Sivas’ta yoğun kar yağışı nedeniyle yaşanan mağduriyetlere ve Hükûmetten acil yardım talebine ilişkin açıklaması", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d24/c015/tbmm24015074.pdf", "sayfa": ["582"]}]}
{"name": "Sosyal Yardımlaşma ve Dayanışmayı Teşvik Fonundan yapılan yardımlara ilişkin sorusu ve Devlet Bakanı ve Başbakan Yardımcısı Hayati Yazıcı’nın cevabı (7/2327)", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d23/c018/tbmm23018090.pdf", "sayfa": ["735:740"]}]}
{"name": "Muğla Milletvekili Metin Ergun’un, bir belediyenin kanalizasyon pro-jesine (6/250), Antalya Milletvekili Tayfur Süner’in, Antalya-Yamansaz bölgesindeki yapılaşmaya (6/313) ve Serik Tapu Müdürlüğüne (6/314), Ordu Milletvekili Rıdvan Yalçın’ın, Belediyelere yapılan acil ödenek yardımlarına (6/345) ve Kamuda bahşişle ilgili bir açıklamasına (6/510), Gaziantep Milletvekili Hasan Özdemir’in, diğer illerden Gaziantep’e yapılan göçe (6/402), Gaziantep Milletvekili Yaşar Ağyüz’ün, Tapu ve Kadastro Genel Müdürünün bahşişle ilgili açıklamasına (6/466), Antalya Milletvekili Hüsnü Çöllü’nün, bahşişle ilgili açıklamalara (6/467) ve Tokat Milletvekili Reşat Doğru’nun, Personel maaşlarını iyileştirme çalışmalarına (6/496) ve Belediyelere yapılacak afet yardımlarına (6/509), ilişkin sözlü soru önergeleri münasebetiyle", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d23/c019/tbmm23019093.pdf", "sayfa": ["50:54"]}]}
{"name": "Belediyelere yapılan yardımlara ilişkin sorusu ve İçişleri Bakanı Meral Akşener'in cevabı (7/1625)", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d20/c017/tbmm20017036.pdf", "sayfa": ["543:544"]}]}
{"name": "Başbakan ve bir grup bakanın deprem bölgesinde yaptıkları durum değerlendirmesinde belediye başkanı ve yardımcısıyla diyalog kurulmadığına ilişkin açıklaması", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d24/c003/tbmm24003011.pdf", "sayfa": ["39"]}]}
{"name": "Sosyal yardımlaşma ve dayanışma vakıfları çalışanlarının sorunlarına ilişkin açıklaması", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d26/c017/tbmm26017087.pdf", "sayfa": ["246"]}]}
{"name": "Sosyal güvenlik il müdürleri ve müdür yardımcılarına ilişkin sorusu ve Çalışma ve Sosyal Güvenlik Bakanı Faruk Çelik’in cevabı (7/2755)", "links": [{"link": "https://www.tbmm.gov.tr/tutanaklar/TUTANAK/TBMM/d23/c019/tbmm23019098.pdf", "sayfa": ["1009:1013"]}]}
